### ISSUE TITLE
Sort iPad meal picker by meal name

### ISSUE THREAD

**Issue by justinanderson** [MIT-Mobile/MIT-Mobile-for-iOS#832]
Looks like they're sorted by start time right now, but sometimes there's a mismatch between the hours and menu items, making dining hall both closed for a meal but having items on the menu for that meal. The meals for each day should always be sorted Breakfast, Brunch, Lunch, then Dinner.

**Comment by rosslebeau** [comment]
@justinanderson can you give me an example of where this is happening? or a sample json response that is valid but would cause this issue?

**Comment by justinanderson** [comment]
@rosslebeau I'll whip up some sample data.

**Comment by LoganWright** [comment]
@justinanderson - Just wanted to check in and see if the sample data was ready so we could dig in to this.

**Comment by LoganWright** [comment]
@justinanderson - I think I found the issue, but now I'm unsure of the expected behavior.  At the moment, the open / closed is based on the current time (ie `[NSDate date]`) as opposed to the time of the meal visible.

So for instance, when looking at breakfast on thursday on monday at midnight, the restaurant would show closed because it's not open on monday at midnight.

I changed the behavior to show open or closed based on the currently visible meal, let me know if this is desired behavior and I'll put up a PR.

**Comment by LoganWright** [comment]
@justinanderson - Ok, I was able to find the incorrect order bug today, and I have a PR up now that will resolve that issue.  The day selector is now always prioritized to the left, Breakfast, Brunch, Lunch, Dinner.

The issue w/ restaurants showing closed is still there, but I have a commit ready with the changes I discussed above if you'd like me to merge that in.  Sorry about the several messages, just wanted to keep you updated on this one.

**Comment by justinanderson** [comment]
@LoganWright That shows a problem with the Dining UI on iPads. The visual hierarchy on an iPhone is: dining hall name, is it open or not, pick a meal, see the hours for that meal. On the iPad it's pick a meal, then see a single line with a dining hall's name, hours, and open/closed status. It ends up looking like the status of that meal rather than the status of the hall itself.

The open/closed flags are doing the right thing right now, since it's supposed to be the open/closed state of the dining hall at this moment. I'll open a new issue to improve the UI.
